// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package history

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type message_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var MessageBinding = message_EntityInfo{
	Entity: objectbox.Entity{
		Id: 1,
	},
	Uid: 255373220643024706,
}

// Message_ contains type-based Property helpers to facilitate some common operations such as Queries.
var Message_ = struct {
	Id        *objectbox.PropertyUint64
	SessionID *objectbox.PropertyString
	Role      *objectbox.PropertyString
	Content   *objectbox.PropertyString
	CreatedAt *objectbox.PropertyInt64
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &MessageBinding.Entity,
		},
	},
	SessionID: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &MessageBinding.Entity,
		},
	},
	Role: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &MessageBinding.Entity,
		},
	},
	Content: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &MessageBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyInt64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &MessageBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (message_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (message_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Message", 1, 255373220643024706)
	model.Property("Id", 6, 1, 3874143154987008719)
	model.PropertyFlags(1)
	model.Property("SessionID", 9, 2, 5710854684500624441)
	model.Property("Role", 9, 3, 1941180788835896938)
	model.Property("Content", 9, 4, 8691141257097638136)
	model.Property("CreatedAt", 10, 5, 798435374010305242)
	model.EntityLastPropertyId(5, 798435374010305242)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (message_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*Message).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (message_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*Message).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (message_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (message_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*Message)
	var propCreatedAt int64
	{
		var err error
		propCreatedAt, err = objectbox.TimeInt64ConvertToDatabaseValue(obj.CreatedAt)
		if err != nil {
			return errors.New("converter objectbox.TimeInt64ConvertToDatabaseValue() failed on Message.CreatedAt: " + err.Error())
		}
	}

	var offsetSessionID = fbutils.CreateStringOffset(fbb, obj.SessionID)
	var offsetRole = fbutils.CreateStringOffset(fbb, obj.Role)
	var offsetContent = fbutils.CreateStringOffset(fbb, obj.Content)

	// build the FlatBuffers object
	fbb.StartObject(5)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetSessionID)
	fbutils.SetUOffsetTSlot(fbb, 2, offsetRole)
	fbutils.SetUOffsetTSlot(fbb, 3, offsetContent)
	fbutils.SetInt64Slot(fbb, 4, propCreatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (message_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'Message' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	propCreatedAt, err := objectbox.TimeInt64ConvertToEntityProperty(fbutils.GetInt64Slot(table, 12))
	if err != nil {
		return nil, errors.New("converter objectbox.TimeInt64ConvertToEntityProperty() failed on Message.CreatedAt: " + err.Error())
	}

	return &Message{
		Id:        propId,
		SessionID: fbutils.GetStringSlot(table, 6),
		Role:      fbutils.GetStringSlot(table, 8),
		Content:   fbutils.GetStringSlot(table, 10),
		CreatedAt: propCreatedAt,
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (message_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Message, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (message_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*Message), nil)
	}
	return append(slice.([]*Message), object.(*Message))
}

// Box provides CRUD access to Message objects
type MessageBox struct {
	*objectbox.Box
}

// BoxForMessage opens a box of Message objects
func BoxForMessage(ob *objectbox.ObjectBox) *MessageBox {
	return &MessageBox{
		Box: ob.InternalBox(1),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Message.Id property on the passed object will be assigned the new ID as well.
func (box *MessageBox) Put(object *Message) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the Message.Id property on the passed object will be assigned the new ID as well.
func (box *MessageBox) Insert(object *Message) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *MessageBox) Update(object *Message) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *MessageBox) PutAsync(object *Message) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the Message.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the Message.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *MessageBox) PutMany(objects []*Message) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *MessageBox) Get(id uint64) (*Message, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*Message), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *MessageBox) GetMany(ids ...uint64) ([]*Message, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Message), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *MessageBox) GetManyExisting(ids ...uint64) ([]*Message, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*Message), nil
}

// GetAll reads all stored objects
func (box *MessageBox) GetAll() ([]*Message, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*Message), nil
}

// Remove deletes a single object
func (box *MessageBox) Remove(object *Message) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *MessageBox) RemoveMany(objects ...*Message) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the Message_ struct to create conditions.
// Keep the *MessageQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *MessageBox) Query(conditions ...objectbox.Condition) *MessageQuery {
	return &MessageQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the Message_ struct to create conditions.
// Keep the *MessageQuery if you intend to execute the query multiple times.
func (box *MessageBox) QueryOrError(conditions ...objectbox.Condition) (*MessageQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &MessageQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See MessageAsyncBox for more information.
func (box *MessageBox) Async() *MessageAsyncBox {
	return &MessageAsyncBox{AsyncBox: box.Box.Async()}
}

// MessageAsyncBox provides asynchronous operations on Message objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type MessageAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForMessage creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use MessageBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForMessage(ob *objectbox.ObjectBox, timeoutMs uint64) *MessageAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 1, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 1: %s" + err.Error())
	}
	return &MessageAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *MessageAsyncBox) Put(object *Message) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *MessageAsyncBox) Insert(object *Message) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *MessageAsyncBox) Update(object *Message) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *MessageAsyncBox) Remove(object *Message) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all Message which Id is either 42 or 47:
//
// box.Query(Message_.Id.In(42, 47)).Find()
type MessageQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *MessageQuery) Find() ([]*Message, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*Message), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *MessageQuery) Offset(offset uint64) *MessageQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *MessageQuery) Limit(limit uint64) *MessageQuery {
	query.Query.Limit(limit)
	return query
}
